spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    username: root
    password: mysql123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally-quoted-identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    sql:
      init:
        mode: never

